imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# KsCoreBundle configuration
ks_core:
    pwd_management: local
    # login_security: none or lock, to come: captcha
    login_security: lock
    login_security_threshold: 4
    ldap_user_dn: "CN={username},OU=Users,DC=maxcrc,DC=com"

# KsAdminBundle configuration
#ks_admin:
#    app_name: MyApp

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: es
    security.exception_listener.class: Ks\CoreBundle\Security\Firewall\ExceptionListener

framework:
    #esi:             ~
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    trusted_hosts:   ~
    trusted_proxies: ~
    fragments:       ~
    http_method_override: true
    default_locale:  "%locale%"
    translator:      { fallbacks: [es] }
    validation:      { enable_annotations: true }
    session:
        handler_id: session.handler.pdo

# Twig Configuration
twig:
    debug: "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Monolog Configuration
monolog:
    handlers:
        applog:
            type: rotating_file
            path: "%kernel.root_dir%/logs/app.log"
            level: info
            max_files: 7
            formatter: monolog.formatter.session_request

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver:   '%database_driver%'
                host:     '%database_host%'
                port:     '%database_port%'
                dbname:   '%database_name%'
                user:     '%database_user%'
                password: '%database_password%'
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        entity_managers:
            default:
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                # StofDoctrineExtensionsBundle Configuration
                mappings:
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false

# StofDoctrineExtensionsBundle Configuration
stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            loggable: true
            timestampable: true
